// src/lib/components/TextInput.svelte
<script lang="ts">
import { appState } from "$lib/state.svelte";

function _handleKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
    e.preventDefault();
    appState.processText(appState.textInput);
  }
}

async function _handleTransform() {
  await appState.processText(appState.textInput);
}
</script>

<div class="input-panel" class:visible={appState.inputMode === 'text'}>
	<div class="panel-header">
		<span class="panel-number">02</span>
		<span class="panel-label">RAW INPUT FORM</span>
		<span class="panel-status">REQUIRED FIELD</span>
	</div>
	
	<textarea
		id="text-input"
		bind:value={appState.textInput}
		onkeydown={handleKeyDown}
		placeholder="ENTER UNPROFESSIONAL TEXT HERE...&#10;&#10;Example: This is bullshit. Why can't you idiots figure this out?"
		rows="8"
	></textarea>
	
	<div class="button-row">
		<button 
			class="transform-btn"
			onclick={handleTransform}
			disabled={!appState.textInput.trim() || appState.isProcessing}
		>
			{#if appState.isProcessing}
				<span class="spinner"></span> PROCESSING...
			{:else}
				▶ GENERATE PROFESSIONAL TEXT
			{/if}
		</button>
		<span class="shortcut-hint">CTRL+ENTER</span>
	</div>
</div>

<style>
	.input-panel {
		display: none;
		background: #f5f0e6;
		border: 2px solid #5a5a5a;
		border-top: none;
		padding: 1rem;
	}

	.input-panel.visible {
		display: block;
	}

	.panel-header {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		margin-bottom: 1rem;
		padding-bottom: 0.5rem;
		border-bottom: 1px dashed #c9b896;
	}

	.panel-number {
		font-family: 'Courier New', monospace;
		font-size: 0.75rem;
		font-weight: bold;
		color: #c9b896;
		background: #1a1a1a;
		padding: 0.25rem 0.5rem;
	}

	.panel-label {
		font-family: 'Arial', sans-serif;
		font-size: 0.75rem;
		font-weight: bold;
		letter-spacing: 0.1em;
		color: #5a5a5a;
		flex: 1;
	}

	.panel-status {
		font-family: 'Courier New', monospace;
		font-size: 0.625rem;
		color: #8a4a4a;
		background: #f5e6e6;
		padding: 0.125rem 0.5rem;
		border: 1px solid #8a4a4a;
	}

	textarea {
		width: 100%;
		padding: 1rem;
		background: #fff;
		border: 2px solid #c9b896;
		color: #1a1a1a;
		font-family: 'Courier New', monospace;
		font-size: 0.875rem;
		resize: vertical;
		transition: border-color 0.2s;
	}

	textarea:focus {
		outline: none;
		border-color: #c9b896;
		box-shadow: inset 0 0 0 2px rgba(201, 184, 150, 0.2);
	}

	textarea::placeholder {
		color: #8a8a8a;
	}

	.button-row {
		display: flex;
		align-items: center;
		gap: 1rem;
		margin-top: 1rem;
	}

	.transform-btn {
		flex: 1;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
		padding: 0.75rem 1.5rem;
		background: #2a2a2a;
		color: #d4c5a9;
		border: 2px solid #5a5a5a;
		font-family: 'Courier New', monospace;
		font-size: 0.75rem;
		font-weight: bold;
		letter-spacing: 0.1em;
		text-transform: uppercase;
		cursor: pointer;
		transition: all 0.15s ease;
	}

	.transform-btn:hover:not(:disabled) {
		background: #3d3d3d;
		border-color: #c9b896;
		color: #d4c5a9;
	}

	.transform-btn:disabled {
		background: #4a4a4a;
		color: #6a6a6a;
		cursor: not-allowed;
	}

	.spinner {
		width: 12px;
		height: 12px;
		border: 2px solid #c9b896;
		border-top-color: transparent;
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
	}

	@keyframes spin {
		to { transform: rotate(360deg); }
	}

	.shortcut-hint {
		font-family: 'Courier New', monospace;
		font-size: 0.625rem;
		color: #6a6a6a;
		background: #e0dcc8;
		padding: 0.25rem 0.5rem;
		border: 1px dashed #5a5a5a;
	}
</style>

// src/lib/components/TextInput.vue
<template>
  <div class="text-panel" v-show="inputMode === 'text'">
    <div class="panel-header">
      <span class="panel-id">FORM 02</span>
      <span class="panel-title">RAW INPUT DOCUMENT</span>
      <span class="panel-badge">* REQUIRED</span>
    </div>
    
    <div class="form-field">
      <label for="raw-input" class="field-label">ENTER UNPROFESSIONAL TEXT BELOW:</label>
      <textarea
        id="raw-input"
        v-model="textInput"
        @keydown="handleKeyDown"
        placeholder="Type your raw, unfiltered thoughts here...&#10;&#10;Example: This is bullshit. Why can't you idiots figure this out? I'm sick of explaining the same damn thing."
        rows="8"
        class="vintage-textarea"
      ></textarea>
      <div class="field-note">
        <span class="note-icon">📝</span>
        All submissions will be processed according to TPS Report guidelines
      </div>
    </div>
    
    <div class="action-row">
      <button 
        class="submit-btn"
        :class="{ processing: isProcessing }"
        @click="handleTransform"
        :disabled="!textInput.trim() || isProcessing"
      >
        <span v-if="isProcessing" class="spinner"></span>
        <span class="btn-text">
          {{ isProcessing ? 'PROCESSING...' : '▶ GENERATE PROFESSIONAL TEXT' }}
        </span>
      </button>
      <div class="shortcut-badge">
        <kbd>CTRL</kbd>+<kbd>ENTER</kbd>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { processText, textInput } from "$lib/state";

function _handleKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
    e.preventDefault();
    handleTransform();
  }
}

function handleTransform() {
  processText(textInput.value);
}
</script>

<style scoped>
.text-panel {
  background: #f5f0e6;
  border: 2px solid #4a4a4a;
  padding: 1.5rem;
}

.panel-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 1rem;
  padding-bottom: 0.75rem;
  border-bottom: 2px dashed #c9b896;
}

.panel-id {
  font-family: 'VT323', monospace;
  font-size: 0.9rem;
  background: #1a1a1a;
  color: #00ff41;
  padding: 0.25rem 0.5rem;
}

.panel-title {
  font-family: 'Courier Prime', monospace;
  font-size: 0.85rem;
  font-weight: bold;
  letter-spacing: 0.1em;
  color: #4a4a4a;
  flex: 1;
}

.panel-badge {
  font-family: 'VT323', monospace;
  font-size: 0.8rem;
  padding: 0.25rem 0.5rem;
  background: #fce4ec;
  color: #b71c1c;
  border: 1px solid #b71c1c;
}

.form-field {
  margin-bottom: 1.5rem;
}

.field-label {
  display: block;
  font-family: 'Courier Prime', monospace;
  font-size: 0.75rem;
  font-weight: bold;
  color: #4a4a4a;
  margin-bottom: 0.5rem;
  letter-spacing: 0.05em;
}

.vintage-textarea {
  width: 100%;
  padding: 1rem;
  font-family: 'VT323', monospace;
  font-size: 1.15rem;
  line-height: 1.5;
  background: #fefef9;
  border: 2px solid #4a4a4a;
  color: #1a1a1a;
  resize: vertical;
  min-height: 180px;
  box-shadow: 
    inset 3px 3px 6px rgba(0,0,0,0.1),
    inset -1px -1px 0 rgba(255,255,255,0.5);
}

.vintage-textarea:focus {
  outline: none;
  border-color: #b22222;
  box-shadow: 
    inset 3px 3px 6px rgba(0,0,0,0.1),
    0 0 0 3px rgba(178, 34, 34, 0.2);
}

.vintage-textarea::placeholder {
  color: #a8a8a8;
  font-style: italic;
}

.field-note {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-top: 0.5rem;
  font-family: 'Special Elite', monospace;
  font-size: 0.8rem;
  color: #7a7a7a;
  font-style: italic;
}

.note-icon {
  font-size: 1rem;
}

.action-row {
  display: flex;
  align-items: center;
  gap: 1rem;
  flex-wrap: wrap;
}

.submit-btn {
  flex: 1;
  min-width: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
  padding: 1rem 1.5rem;
  font-family: 'VT323', monospace;
  font-size: 1.1rem;
  letter-spacing: 0.1em;
  background: linear-gradient(180deg, #dc143c 0%, #b22222 50%, #8b0000 100%);
  color: white;
  border: 3px solid #8b0000;
  box-shadow: 
    0 4px 0 #5a0000,
    0 6px 10px rgba(0,0,0,0.3);
  cursor: pointer;
  transition: all 0.15s;
  position: relative;
  top: 0;
}

.submit-btn:hover:not(:disabled) {
  background: linear-gradient(180deg, #ff1744 0%, #dc143c 50%, #b22222 100%);
}

.submit-btn:active:not(:disabled) {
  top: 4px;
  box-shadow: 
    0 0 0 #5a0000,
    0 2px 5px rgba(0,0,0,0.3);
}

.submit-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.submit-btn.processing {
  background: linear-gradient(180deg, #7a7a7a 0%, #5a5a5a 50%, #4a4a4a 100%);
  border-color: #4a4a4a;
  box-shadow: 0 4px 0 #2a2a2a, 0 6px 10px rgba(0,0,0,0.3);
}

.spinner {
  width: 18px;
  height: 18px;
  border: 3px solid rgba(255,255,255,0.3);
  border-top-color: white;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.shortcut-badge {
  font-family: 'VT323', monospace;
  font-size: 0.85rem;
  color: #7a7a7a;
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.shortcut-badge kbd {
  background: #e8e4d9;
  border: 1px solid #a8a8a8;
  border-bottom-width: 2px;
  padding: 0.2rem 0.4rem;
  border-radius: 3px;
  font-family: inherit;
}
</style>
